In [1]:
import numpy as np

In [42]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]], dtype=np.float32)
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]], dtype=float32)

In [43]:
a.shape, a.dtype, a.ndim

((2, 5), dtype('float32'), 2)

In [44]:
a.astype(np.int32)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
a.reshape(-1, 2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]], dtype=float32)

In [47]:
a.ravel(), a #не возвращает копию

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32),
 array([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]], dtype=float32))

In [48]:
a.flatten(), a

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32),
 array([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]], dtype=float32))

In [51]:
a.transpose()

array([[ 1.,  6.],
       [ 2.,  7.],
       [ 3.,  8.],
       [ 4.,  9.],
       [ 5., 10.]], dtype=float32)

In [54]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
b.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
b[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [57]:
b[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [58]:
b[np.newaxis, :, np.newaxis]

array([[[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]])

In [60]:
c = np.copy(a)
a[0, 0] = 2
a, c

(array([[ 2.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]], dtype=float32),
 array([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]], dtype=float32))

In [61]:
np.random.seed(221)

a = np.random.randint(0, 10, size=(3, 6))
a

array([[6, 4, 2, 9, 5, 3],
       [8, 7, 6, 4, 0, 2],
       [7, 4, 2, 1, 0, 1]])

In [63]:
a.max(axis=0), a.min(axis=1)

(array([8, 7, 6, 9, 5, 3]), array([2, 0, 0]))

In [64]:
a.sum()

71

In [65]:
a.argmax()

3

In [66]:
a.ravel()[a.argmax()]

9

In [73]:
np.unravel_index(a.argmax(), a.shape)

(0, 3)

In [74]:
np.random.seed(583)

a = np.random.randint(0, 10, size=(3, 6))
b = np.random.randint(0, 10, size=(3, 6))
a, b

(array([[9, 1, 1, 0, 0, 8],
        [6, 3, 5, 7, 4, 2],
        [0, 5, 7, 8, 8, 1]]),
 array([[1, 9, 0, 1, 5, 9],
        [3, 9, 8, 9, 0, 3],
        [8, 6, 9, 2, 6, 8]]))

In [76]:
np.fmax(a, b), np.fmin(a, b)

(array([[9, 9, 1, 1, 5, 9],
        [6, 9, 8, 9, 4, 3],
        [8, 6, 9, 8, 8, 8]]),
 array([[1, 1, 0, 0, 0, 8],
        [3, 3, 5, 7, 0, 2],
        [0, 5, 7, 2, 6, 1]]))

In [77]:
np.isclose(a, b)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [79]:
np.matmul(a, b.reshape(6, -1))

array([[ 29, 143,  81],
       [123, 150, 140],
       [164, 142, 205]])

In [80]:
a[a > 5], b[b < 5]

(array([9, 8, 6, 7, 7, 8, 8]), array([1, 0, 1, 3, 0, 3, 2]))

In [83]:
c = a < 5 # маска
c

array([[False,  True,  True,  True,  True, False],
       [False,  True, False, False,  True,  True],
       [ True, False, False, False, False,  True]])